%YAML:1.0
#for urop2019s testing
#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 2  

imu_topic: "/mynteye/imu/data_raw"
image0_topic: "/mynteye/left/image_raw"
image1_topic: "/mynteye/right/image_raw"
output_path: "/home/dji/catkin_ws/src/VINS-Fusion/output/"

cam0_calib: "left_pinhole.yaml"
cam1_calib: "right_pinhole.yaml"
image_width: 640
image_height: 400
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ -9.9825050839976948e-01, -1.3145700969011239e-02, 5.7646448508431994e-02, -2.4863392028054303e-02,
   1.1063047891614532e-02, -9.9927971703244811e-01, -3.6299533039671150e-02, 1.6006236337252186e-01,
   5.8082109560085776e-02, -3.5598281890895672e-02, 9.9767691708060813e-01,  3.3204549407966966e-02 ,
 0., 0., 0., 1. ]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ -9.9860164071934587e-01, 2.4222688366984111e-03, -5.2809996840685554e-02, -6.3895986687404926e-02,
  	-3.2166478890890025e-03, -9.9988288290542071e-01, 1.4962407864451473e-02, 1.6605232198265263e-01,
      -5.2767568912998809e-02, 1.5111356207413672e-02, 9.9849247898248317e-01, 1.3350888533558850e-02, 
	0., 0., 0., 1. ]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.01          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.001         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.0001        # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 0.00001       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.8         # gravity magnitude

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/xinjie/VINS_ws/src/VINS-Mono/output/pose_graph/" # save and load path
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
